import{S as y,a as c,i as g}from"./assets/vendor-bad0427b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const d=document.querySelector(".loader"),h=document.querySelector(".img-information"),u=document.querySelector(".input-img-name"),n=document.querySelector(".fetch-more-button");new y(".gallery a",{captionDelay:250,captionsData:"alt",close:!0});let i=1,p=20;c.create({baseURL:"https://pixabay.com/api/",headers:{"Content-Type":"application/json"},page:i,per_page:p});function L(){d.style.display="block"}function b(){d.style.display="none"}const w=()=>{const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})};n.addEventListener("click",async()=>{let{hits:s,totalHits:t}=m(u.value);f(s),w();const r=Math.ceil(t/p);i>r&&(n.style.display="none",n.textContent="We're sorry, but you've reached the end of search results.")});let v={key:"41575459-699006cd61f4fecce9ea2d52d",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0};async function m(s){const t=new URLSearchParams(v);L();try{const r=await c.get(`https://pixabay.com/api/?${t}`);return i+=1,i>1&&n.classList.add("visible-btn"),b(),r.data}catch(r){g.error({title:"Error",message:r.message,position:"topRight"})}}function f(s){const t=document.querySelector(".gallery"),r=s.reduce((a,e)=>a+`<li class="gallery-item">
         <a class="image-link" href="${e.largeImageURL}">
         <img class="images" data-source="${e.largeImageURL}" alt="${e.tags}" src="${e.webformatURL}" width="360" height="200">
         </a>
         <div class="information">
         <p>Likes: ${e.likes}</p>
         <p>Views: ${e.views}</p>
         <p>Comments: ${e.comments}</p>
         <p>Downloads: ${e.downloads}</p>
        </div>
      </li>`,"");t.insertAdjacentHTML("beforeend",r)}h.addEventListener("submit",async s=>{s.preventDefault();let{hits:t,totalHits:r}=await m(u.value);f(t)});
//# sourceMappingURL=commonHelpers.js.map
