import{S as h,i as d,a as b}from"./assets/vendor-bad0427b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const y=document.querySelector(".loader"),p=document.querySelector(".loader-before-button"),L=document.querySelector(".img-information");document.querySelector(".input-img-name");const l=document.querySelector(".fetch-more-button"),m=document.querySelector(".gallery"),w=new h(".gallery a",{captionDelay:250,captionsData:"alt",close:!0});let a=1,i,u=40;const S=()=>{const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})};async function g(s,e){const n="https://pixabay.com/api/",o="41530032-c682b7302a1559a8b9f540776";try{return(await b.get(`${n}`,{params:{key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:u}})).data}catch(t){d.error({title:"Error",message:t.message,position:"topRight"})}}l.addEventListener("click",async s=>{p.style.display="block",l.style.display="none";try{a+=1;const{hits:e,totalHits:n}=await g(i,a),o=Math.ceil(n/u);if(l.style.display="block",f(e),S(),a===o)return l.style.display="none",d.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(e){console.log(e)}finally{p.style.display="none"}});L.addEventListener("submit",async s=>{if(s.preventDefault(),y.style.display="block",l.style.display="none",a=1,i=s.target.elements.search.value.trim(),i===""){l.style.display="none";return}try{const{hits:e,totalHits:n}=await g(i,a);e.length>0?(y.style.display="none",f(e),l.style.display="block"):(m.innerHTML="",d.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),n<=u&&(l.style.display="none")}catch(e){console.log(e.message)}finally{y.style.display="none",s.target.reset()}});function f(s=[]){const e=s.reduce((n,o)=>n+`<li class="gallery-item">
         <a class="image-link" href="${o.largeImageURL}">
         <img class="images" data-source="${o.largeImageURL}" alt="${o.tags}" src="${o.webformatURL}" width="360" height="200">
         </a>
         <div class="information">
         <p>Likes: ${o.likes}</p>
         <p>Views: ${o.views}</p>
         <p>Comments: ${o.comments}</p>
         <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`,"");m.insertAdjacentHTML("beforeend",e),w.refresh()}
//# sourceMappingURL=commonHelpers.js.map
