import{S as m,a as d,i as u}from"./assets/vendor-bad0427b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const p=document.querySelector(".loader"),f=document.querySelector(".img-information"),g=document.querySelector(".input-img-name"),c=document.querySelector(".fetch-more-button"),y=new m(".gallery a",{captionDelay:250,captionsData:"alt",close:!0});let s=1,h=40;d.create({baseURL:"https://pixabay.com/api/",headers:{"Content-Type":"application/json"}});function b(){p.style.display="block"}function L(){p.style.display="none"}const w=()=>{const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})};let l={key:"41575459-699006cd61f4fecce9ea2d52d",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:h};const v=new URLSearchParams(l);async function I(r){l.q=r,b();try{l.page=1;const t=await d.get(`https://pixabay.com/api/?${v}`);return s+=1,s>1&&c.classList.add("visible-btn"),L(),t.data}catch(t){u.error({title:"Error",message:t.message,position:"topRight"})}}function S(r){const t=document.querySelector(".gallery"),n=r.reduce((a,e)=>a+`<li class="gallery-item">
         <a class="image-link" href="${e.largeImageURL}">
         <img class="images" data-source="${e.largeImageURL}" alt="${e.tags}" src="${e.webformatURL}" width="360" height="200">
         </a>
         <div class="information">
         <p>Likes: ${e.likes}</p>
         <p>Views: ${e.views}</p>
         <p>Comments: ${e.comments}</p>
         <p>Downloads: ${e.downloads}</p>
        </div>
      </li>`,"");t.insertAdjacentHTML("beforeend",n),y.refresh()}c.addEventListener("click",async()=>{await I(q),w()});f.addEventListener("submit",async r=>{r.preventDefault(),s=1,g.value,S(hits),s===totalPages&&(c.style.display="none",u.error({title:"Message",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))});
//# sourceMappingURL=commonHelpers.js.map
